[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = false

[colors.bright]
black = "#5b6078"
blue = "#8aadf4"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#f5bde6"
red = "#ed8796"
white = "#a5adcb"
yellow = "#eed49f"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#494d64"
blue = "#8aadf4"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#f5bde6"
red = "#ed8796"
white = "#b8c0e0"
yellow = "#eed49f"

[colors.normal]
black = "#494d64"
blue = "#8aadf4"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#f5bde6"
red = "#ed8796"
white = "#b8c0e0"
yellow = "#eed49f"

[colors.primary]
background = "#222436"
bright_foreground = "#cad3f5"
dim_foreground = "#a5adcb"
foreground = "#cad3f5"

[colors.search.focused_match]
background = "#f4dbd6"
foreground = "#24273a"

[colors.search.matches]
background = "#a5adcb"
foreground = "#24273a"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

[cursor.vi_mode_style]
blinking = "On"
shape = "Block"

[font]
size = 19.0

[font.normal]
family = "CaskaydiaMono NF"

[font.offset]
x = 0
y = 2

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 5

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"

[terminal.shell]
args = ["-l"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Windowed"

[window.dimensions]
columns = 66
lines = 25
