#!/bin/sh


bspc monitor -d 1 2 3 4 # I II III IV ⅠⅡ Ⅲ Ⅳ

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config focus_follows_pointer false

# Window borders (Auto-Generate)
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 1
bspc config borderless_monocle true

bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# fix pointer
xsetroot -cursor_name left_ptr

# gaps
bspc config gapless_monocle true
bspc config window_gap 7

# moving floating windows and resize them with mouse, hold alt key
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# rules

bspc rule -a feh state=floating

# start resources

bluetoothctl connect C9:18:0D:A4:F9:23 &

xrdb merge ~/.Xresources

xrandr --output DVI-D-0 --mode 1920x1080

feh --bg-fill ~/pctrs/wallp/default/17.png &

picom &

polybar example &
